In [2]:
import numpy as np
import pandas as pd
import os

In [4]:
train=pd.read_csv("train.csv")

In [7]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
test=pd.read_csv("test.csv")

In [9]:
import pycaret

#### PassengerID is of no such use hence will be ignored by lib
#### Name and ticket will also be ignored while modeling

In [13]:
from pycaret.classification import *
clf1=setup(train,target="Survived",ignore_features=['Name','PassengerId','Ticket'])

Setup Succesfully Completed!

### Comparing Different classification models

In [14]:
compare_models()

#### GD classifier gives highest accuracy

In [15]:
tuned_lightgbm = tune_model('lightgbm',optimize='AUC')

      Accuracy     AUC  Recall   Prec.      F1   Kappa
0       0.7937  0.8600  0.6250  0.7895  0.6977  0.5442
1       0.7937  0.8269  0.7500  0.7200  0.7347  0.5660
2       0.8413  0.8349  0.6667  0.8889  0.7619  0.6465
3       0.8548  0.8586  0.7500  0.8571  0.8000  0.6869
4       0.7903  0.8372  0.6250  0.7895  0.6977  0.5405
5       0.7742  0.8010  0.5417  0.8125  0.6500  0.4930
6       0.8226  0.8860  0.7083  0.8095  0.7556  0.6173
7       0.7742  0.8311  0.7083  0.7083  0.7083  0.5241
8       0.8548  0.9474  0.8750  0.7778  0.8235  0.7010
9       0.8226  0.8941  0.7826  0.7500  0.7660  0.6232
Mean    0.8122  0.8577  0.7033  0.7903  0.7395  0.5943
SD      0.0296  0.0400  0.0894  0.0534  0.0497  0.0674

In [16]:
evaluate_model(tuned_lightgbm)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [17]:
final_lightgbm=finalize_model(tuned_lightgbm)

In [18]:
print(final_lightgbm)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.6, max_depth=90,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.2,
               n_estimators=30, n_jobs=-1, num_leaves=150, objective=None,
               random_state=796, reg_alpha=0.4, reg_lambda=0.2, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [19]:
predictions = predict_model(final_lightgbm, data=test)

In [20]:
predictions.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Label,Score
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,0.0450
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0,0.2261
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,0.1167
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,0.2147
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0,0.2500

In [21]:
predictions

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Label,Score
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,0.0450
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0,0.2261
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,0.1167
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,0.2147
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0,0.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,0.0658
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1,0.9890
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,0.0057
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,0.0658
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0,0.1703